# Generated by Django 4.1.1 on 2022-10-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="owner",
            new_name="user",
        ),
    ]
